// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp2.Data.Context;

#nullable disable

namespace Tp2.Migrations
{
    [DbContext(typeof(MonsterContext))]
    partial class MonsterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tp2.Models.Monster", b =>
                {
                    b.Property<int>("IdMonster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMonster"));

                    b.Property<int>("DefenseBase")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceBase")
                        .HasColumnType("int");

                    b.Property<int>("ForceBase")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PointsVieBase")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type2")
                        .HasColumnType("longtext");

                    b.HasKey("IdMonster");

                    b.ToTable("Monster");
                });
#pragma warning restore 612, 618
        }
    }
}
